In [1]:
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
%matplotlib inline
import collections
import os
import seaborn
from sklearn.linear_model import SGDClassifier
seaborn.set()

In [ ]:
def printCoefs(classifier):
    # retrieve all the nonzero coefficients and zip them with their respective indices
    nonzeroes = np.nonzero(classifier.coef_[0])[0]
    coefs = zip(nonzeroes, classifier.coef_[0][nonzeroes])

    # sort the coefficients by their value, instead of index
    coefs.sort(key = lambda x: x[1], reverse=True)

    for coef in coefs[:50]:
        print coef

In [ ]:
encoded = np.load("./npy_data/data_encoded_d.npy")

In [ ]:
blood_types = np.load('./npy_data/blood_types.npy')

In [5]:
np.bincount(blood_types)

array([49, 30])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(encoded, blood_types, test_size=0.2)

In [ ]:
X_train.shape

In [12]:
sgd = SGDClassifier(penalty='l1', 
                    class_weight='balanced', 
                    alpha=.3,
                    l1_ratio=1,
                    learning_rate='optimal', 
                    tol=1e-6,
                    max_iter=200,
                    verbose=1)

In [13]:
sgd.fit(X_train, y_train)

-- Epoch 1
Norm: 6281.25, NNZs: 27, Bias: 0.038562, T: 63, Avg. loss: 117576.363361
Total training time: 17.29 seconds.
-- Epoch 2
Norm: 6327.77, NNZs: 6, Bias: -0.236687, T: 126, Avg. loss: 0.194710
Total training time: 35.03 seconds.
-- Epoch 3
Norm: 6351.63, NNZs: 8, Bias: -0.202158, T: 189, Avg. loss: 0.144560
Total training time: 54.64 seconds.
-- Epoch 4
Norm: 6361.62, NNZs: 6, Bias: -0.244740, T: 252, Avg. loss: 0.092730
Total training time: 73.61 seconds.
-- Epoch 5
Norm: 6367.89, NNZs: 6, Bias: -0.259511, T: 315, Avg. loss: 0.089529
Total training time: 91.85 seconds.
-- Epoch 6
Norm: 6372.23, NNZs: 6, Bias: -0.265300, T: 378, Avg. loss: 0.093119
Total training time: 111.20 seconds.
Convergence after 6 epochs took 111.27 seconds


SGDClassifier(alpha=0.3, average=False, class_weight='balanced', epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=1, learning_rate='optimal',
       loss='hinge', max_iter=200, n_iter=None, n_jobs=1, penalty='l1',
       power_t=0.5, random_state=None, shuffle=True, tol=1e-06, verbose=1,
       warm_start=False)

In [14]:
y_pred = sgd.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.875


In [15]:
y_test

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0])

In [16]:
y_pred

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0])

In [1]:
printCoefs(sgd)

NameError: name 'printCoefs' is not defined

In [47]:
linear = LinearSVC(penalty='l1', class_weight='balanced', C=.06, dual=False, verbose=1, max_iter=2500)
linear.fit(X_train, y_train)
print(accuracy_score(y_test, linear.predict(X_test)))

[LibLinear]0.9375


In [52]:
print(linear.predict(X_test))

[0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1]


In [75]:
sgd_cv = SGDClassifier(penalty='l1', 
                    class_weight='balanced', 
                    warm_start=False,
                    alpha=3,
                    l1_ratio=1,
                    learning_rate='optimal', 
                    max_iter=5,
                    verbose=1)

In [77]:
cv_score = cross_val_score(sgd_cv, encoded, blood_types, cv=10, scoring='accuracy')

-- Epoch 1
Norm: 6001.24, NNZs: 6, Bias: 0.080259, T: 71, Avg. loss: 21298.880332
Total training time: 23.94 seconds.
-- Epoch 2
Norm: 6087.43, NNZs: 6, Bias: -0.257098, T: 142, Avg. loss: 0.407446
Total training time: 46.74 seconds.
-- Epoch 3
Norm: 6113.98, NNZs: 5, Bias: -0.334069, T: 213, Avg. loss: 0.155360
Total training time: 69.37 seconds.
-- Epoch 4
Norm: 6125.67, NNZs: 5, Bias: -0.384188, T: 284, Avg. loss: 0.130792
Total training time: 90.01 seconds.
-- Epoch 5
Norm: 6133.16, NNZs: 5, Bias: -0.415039, T: 355, Avg. loss: 0.126522
Total training time: 112.54 seconds.
-- Epoch 1
Norm: 6142.92, NNZs: 4, Bias: 0.000412, T: 71, Avg. loss: 3533.704277
Total training time: 21.47 seconds.
-- Epoch 2
Norm: 6229.65, NNZs: 4, Bias: -0.285743, T: 142, Avg. loss: 0.271008
Total training time: 46.47 seconds.
-- Epoch 3
Norm: 6252.23, NNZs: 3, Bias: -0.293039, T: 213, Avg. loss: 0.121583
Total training time: 67.41 seconds.
-- Epoch 4
Norm: 6263.42, NNZs: 3, Bias: -0.315425, T: 284, Avg. los

In [78]:
print(cv_score.mean(), cv_score.std())

(0.9482142857142858, 0.0846850407241384)


In [19]:
clf = LogisticRegression(penalty='l1', dual=False, C=.5, verbose=1, class_weight='balanced')

In [20]:
clf.fit(X_train, y_train)

[LibLinear]

LogisticRegression(C=0.5, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l1', random_state=None,
          solver='liblinear', tol=0.0001, verbose=1, warm_start=False)

In [21]:
y_pred = clf.predict(X_test)
print(accuracy_score(y_test, y_pred))

1.0


In [22]:
np.argmax(np.abs(clf.coef_))

14151619

In [6]:
from sklearn.ensemble import BaggingClassifier

In [9]:
# time for classifier takes approximately 7 minutes * n_estimators
bag = BaggingClassifier(base_estimator=clf, n_estimators=3)

In [10]:
bag.fit(X_train, y_train)

[LibLinear][LibLinear][LibLinear]

BaggingClassifier(base_estimator=LogisticRegression(C=0.5, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l1', random_state=None,
          solver='liblinear', tol=0.0001, verbose=1, warm_start=False),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=3, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [13]:
y_pred = bag.predict(X_test)

In [14]:
print(accuracy_score(y_test, y_pred))

0.625


In [54]:
y_train_pred = clf.predict(X_train)

In [ ]:
for i in (classifier.coef_[0] > 1e-04):
    if not i == False:
        print("True")

In [5]:
ones = np.nonzero(blood_types)[0]
np.random.shuffle(ones)
zeros = np.where(blood_types == 0)[0]
keep_idx = np.concatenate((zeros, ones[0:15]))

In [9]:
X_train, X_test, y_train, y_test = train_test_split(encoded[keep_idx], blood_types[keep_idx], test_size=0.2)

In [15]:
y_pred = classifier.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.6666666666666666


In [ ]:
# retrieve all the nonzero coefficients and zip them with their respective indices
nonzeroes = np.nonzero(svc.coef_[0])[0]
coefs = zip(nonzeroes, svc.coef_[0][nonzeroes])

# sort the coefficients by their value, instead of index
coefs.sort(key = lambda x: x[1], reverse=True)

for coef in coefs:
    print coef