In [1]:
from sklearn.svm import LinearSVC
from sklearn.linear_model import SGDClassifier
import numpy as np
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
%matplotlib inline
import collections
import os
import seaborn
seaborn.set()

In [2]:
def printCoefs(svc):
    # retrieve all the nonzero coefficients and zip them with their respective indices
    nonzeroes = np.nonzero(svc.coef_[0])[0]
    coefs = zip(nonzeroes, svc.coef_[0][nonzeroes])

    # sort the coefficients by their value, instead of index
    coefs.sort(key = lambda x: x[1], reverse=True)

    for coef in coefs:
        print coef

In [3]:
encoded = np.load("./npy_data/data_encoded_d.npy")

In [4]:
blood_types = np.load('./npy_data/rh_types.npy')

In [4]:
np.bincount(blood_types)

array([15, 64])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(encoded, blood_types, test_size=0.2)

In [12]:
# C = 0.02  # SVM regularization parameter
classifier = LinearSVC(penalty='l1', class_weight='balanced', dual=False, C=1)
svc = classifier.fit(X_train, y_train)

In [13]:
y_pred = classifier.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.8125


In [16]:
y_test

array([1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
for i in (classifier.coef_[0] > 1e-04):
    if not i == False:
        print("True")

In [6]:
ones = np.nonzero(blood_types)[0]
np.random.shuffle(ones)
zeros = np.where(blood_types == 0)[0]
keep_idx = np.concatenate((zeros, ones[0:15]))

In [32]:
results = classifier.predict(encoded[keep_idx])

In [35]:
print(results)

[1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [36]:
print(blood_types[keep_idx])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [34]:
print(accuracy_score(blood_types[keep_idx], results))

0.9


In [27]:
y_pred = classifier.predict(X_test)
print(accuracy_score(y_test, y_pred))

1.0


In [ ]:
keep_idx = np.concatenate((zeros, ones[0:15]))
classifier = LinearSVC(penalty='l1', class_weight='balanced', dual=False, C=1)
for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(encoded[keep_idx], blood_types[keep_idx], test_size=0.2, random_state = i)
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    print(y_pred, y_test)
    print("Accuracy:", accuracy_score(y_pred, y_test))

In [6]:
svc_test = LinearSVC(penalty="l1", class_weight='balanced', dual=False, C=0.05)
cv_scores = cross_val_score(svc_test, encoded[keep_idx], blood_types[keep_idx], cv=10, scoring='accuracy')
print(cv_scores.mean())
print(cv_scores.std())

0.525
0.26100766272276377
