In [1]:
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
%matplotlib inline
import collections
import os
import seaborn
seaborn.set()

In [7]:
encoded = np.load("./npy_data/data_encoded_d.npy")

In [8]:
blood_types = np.load('./npy_data/blood_types.npy')

In [9]:
np.bincount(blood_types)

array([49, 30])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(encoded, blood_types, test_size=0.2)

In [11]:
X_train.shape

(63, 25019446)

In [60]:
clf = SGDClassifier(penalty='l1', 
                    class_weight='balanced', 
                    warm_start=True, 
                    alpha=.01,
                    learning_rate='optimal', 
                    max_iter=6,
                    verbose=1)

In [ ]:
clf = LogisticRegression(penalty='l1', dual=False, C=.06, class_weight='balanced')

In [61]:
clf.fit(X_train, y_train)

-- Epoch 1
Norm: 22289.80, NNZs: 15990549, Bias: -0.015863, T: 63, Avg. loss: 4072384.293315
Total training time: 27.32 seconds.
-- Epoch 2
Norm: 23520.58, NNZs: 13293361, Bias: 0.470659, T: 126, Avg. loss: 482347.930217
Total training time: 52.50 seconds.
-- Epoch 3
Norm: 24318.46, NNZs: 11649556, Bias: 0.510723, T: 189, Avg. loss: 274180.521623
Total training time: 76.02 seconds.
-- Epoch 4
Norm: 24540.22, NNZs: 10694723, Bias: 0.681991, T: 252, Avg. loss: 94677.866162
Total training time: 97.81 seconds.
-- Epoch 5
Norm: 24591.76, NNZs: 9951868, Bias: 0.756364, T: 315, Avg. loss: 1730.793728
Total training time: 117.46 seconds.
-- Epoch 6
Norm: 24598.02, NNZs: 9170713, Bias: 0.519943, T: 378, Avg. loss: 12148.338365
Total training time: 136.84 seconds.


SGDClassifier(alpha=0.01, average=False, class_weight='balanced', epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=6, n_iter=None,
       n_jobs=1, penalty='l1', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=1, warm_start=True)

In [62]:
np.argmax(np.abs(clf.coef_))

14151619

In [63]:
y_pred = clf.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.5


In [65]:
np.bincount(y_test)

array([11,  5])

In [54]:
y_train_pred = clf.predict(X_train)

In [55]:
print(accuracy_score(y_train, y_train_pred))

0.9365079365079365


In [34]:
clf.coef_

array([[0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
for i in (classifier.coef_[0] > 1e-04):
    if not i == False:
        print("True")

In [5]:
ones = np.nonzero(blood_types)[0]
np.random.shuffle(ones)
zeros = np.where(blood_types == 0)[0]
keep_idx = np.concatenate((zeros, ones[0:15]))

In [9]:
X_train, X_test, y_train, y_test = train_test_split(encoded[keep_idx], blood_types[keep_idx], test_size=0.2)

In [15]:
y_pred = classifier.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.6666666666666666


In [ ]:
# retrieve all the nonzero coefficients and zip them with their respective indices
nonzeroes = np.nonzero(svc.coef_[0])[0]
coefs = zip(nonzeroes, svc.coef_[0][nonzeroes])

# sort the coefficients by their value, instead of index
coefs.sort(key = lambda x: x[1], reverse=True)

for coef in coefs:
    print coef